### ISSUE TITLE
Analysis Issue

### ISSUE THREAD

**Issue by maryfollo** [maryfollo/soc513_spring_project#4]
Hi @AaronGullickson 

I was changing the 2012 data like you showed me in office hours yesterday and now my subsets of data aren't working anymore, should I clean out my environment and try again?

Thanks, 
Mary

**Comment by maryfollo** [comment]
@AaronGullickson 

Ok I figured out the 2012 data but I'm writing my paper in the main.intro file and I just added my code chunks and I keep getting an error message that says error in file name, help!

**Comment by AaronGullickson** [comment]
@maryfollo Its probably just the pathway to your dataset. I think the load command should be:

```r
load("../../analysis/output/analytical_data.RData")
```

Basically, `..` means "back a directory." 

If that doesn't help, be sure to push up your latest and I can take a look at the code.

**Comment by maryfollo** [comment]
@AaronGullickson 
ya thats still not working, I just pushed it over for you to look at, thanks!

**Comment by maryfollo** [comment]
@AaronGullickson 

Ok so i created absolute pathways and it knitted all the way until the end and then gave me this error message 

! Undefined control sequence.
l.393 {\centering \includegraphics
                                  {main-Intro__files/figure-latex/vote_age_2...

Error: Failed to compile main-Intro_.tex. See main-Intro_.log for more info.
Execution halted

**Comment by maryfollo** [comment]
@AaronGullickson 

Sorry for all the messages, I was able to get it to knit but I'm still having a small formatting issue, I will be at office hours tomorrow!
